/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static model.Billing.getFeeSummaryData;
import model.DatabaseConnection;
import model.FeeSummary;
import model.marks;
import static model.marks.getMarksByStudentId;
import model.student;
import static model.student.getAllStudents;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DELL
 */
public class ReportPage extends javax.swing.JFrame {

    /**
     * Creates new form ReportPage
     */
    public ReportPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStuDetails = new javax.swing.JButton();
        btnMarksReport = new javax.swing.JButton();
        txtStudentId = new javax.swing.JTextField();
        btnFeeSummaryReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStuDetails.setText("Student Details");
        btnStuDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuDetailsActionPerformed(evt);
            }
        });

        btnMarksReport.setText("Marks Report");
        btnMarksReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarksReportActionPerformed(evt);
            }
        });

        btnFeeSummaryReport.setText("Fee Summary");
        btnFeeSummaryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeSummaryReportActionPerformed(evt);
            }
        });

        btnBack.setText("🔙Back to Dashboard");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Student ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFeeSummaryReport)
                    .addComponent(btnStuDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMarksReport)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStuDetails)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnMarksReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnFeeSummaryReport)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuDetailsActionPerformed
         try {
            // Load the Jasper file
            String jasperPath = "C:\\Users\\DELL\\Documents\\NetBeansProjects\\PrivateTuitionManagementSystem\\src\\main\\resources\\reports\\sd.jasper"; // Path to your compiled .jasper file
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(jasperPath);

            // No parameters
            // Use JREmptyDataSource if no data source is required
            //JRDataSource dataSource = new JREmptyDataSource();
            DatabaseConnection databaseConnection = new DatabaseConnection();
            Connection connection = databaseConnection.getConnection();

            // Fill the report
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, connection);

            // View the report
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error generating report: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnStuDetailsActionPerformed

    private void btnMarksReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarksReportActionPerformed
        String studentIdInput = txtStudentId.getText(); // Assuming you have a JTextField named txtStudentId
    
        if (studentIdInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Student ID.");
            return;
        }

        Connection connection = null;

        try {
            // Parse the input as an integer (assuming student_id is an integer)
            int studentId = Integer.parseInt(studentIdInput);

            // Get the database connection using your custom DatabaseConnection class
            DatabaseConnection databaseConnection = new DatabaseConnection();
            connection = databaseConnection.getConnection();

            // Load the Jasper report
            String jasperPath = "C:\\Users\\DELL\\Documents\\NetBeansProjects\\PrivateTuitionManagementSystem\\src\\main\\resources\\reports\\mr.jasper"; // Path to your compiled .jasper file
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(jasperPath);

            // Pass the student_id parameter
            Map<String, Object> parameters = new HashMap<>();
            parameters.put("student_id", studentId); // Key must match parameter name in the .jrxml file

            // Fill the report with data from the database
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, connection);

            // View the report
            JasperViewer.viewReport(jasperPrint, false);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Student ID must be an integer.");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error generating report: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnMarksReportActionPerformed

    private void btnFeeSummaryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeSummaryReportActionPerformed
      try {
            // Load the Jasper file
            String jasperPath = "C:\\Users\\DELL\\Documents\\NetBeansProjects\\PrivateTuitionManagementSystem\\src\\main\\resources\\reports\\a.jasper"; // Path to your compiled .jasper file
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile(jasperPath);

            // No parameters
            // Use JREmptyDataSource if no data source is required
            //JRDataSource dataSource = new JREmptyDataSource();
            DatabaseConnection databaseConnection = new DatabaseConnection();
            Connection connection = databaseConnection.getConnection();

            // Fill the report
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, connection);

            // View the report
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error generating report: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnFeeSummaryReportActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        ReportPage.this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFeeSummaryReport;
    private javax.swing.JButton btnMarksReport;
    private javax.swing.JButton btnStuDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables

   
}
